### ISSUE TITLE
EDC Data Dashboard for MVD Basic Scenarios

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataDashboard#2]
## Description

The EDC Data Dashboard needs to be extended to allows users to cover the basic scenarios (see agera-edc/MinimumViableDataspace#3) for the Minimum Viable Dataspace.

## Acceptance Criteria

- [x] Scenarios defined in agera-edc/MinimumViableDataspace#3 can be covered through the EDC Data Dashboard

## Stories

- [x] agera-edc/DataDashboardFork#12 (for agera-edc/MinimumViableDataspace#8)
- [x] agera-edc/DataDashboardFork#17
- [x] agera-edc/DataDashboardFork#16 (for agera-edc/MinimumViableDataspace#12)
- [x] agera-edc/DataDashboardFork#13 (for agera-edc/MinimumViableDataspace#13)
- [x] agera-edc/DataDashboardFork#15 (for agera-edc/MinimumViableDataspace#12)
- [x] agera-edc/DataDashboardFork#14 (for agera-edc/MinimumViableDataspace#12)
- [x] agera-edc/DataDashboardFork#11 (for agera-edc/MinimumViableDataspace#6)
- [x] agera-edc/DataDashboardFork#10 (for agera-edc/MinimumViableDataspace#9)
- [x] agera-edc/DataDashboardFork#9
- [x] agera-edc/DataDashboardFork#8
